version: "3.7"
services:
  super-pal-api:
    image: seekheart/super-pal-api
    ports:
      - "8080:8080"
    links:
      - db
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - /data/super_pal:/var/lib/postgresql/data
  super-pal:
    build: .
    env_file:
      - .env
    links:
      - super-pal-api
    depends_on:
      - super-pal-api